# Generated by Django 5.2.8 on 2026-03-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healingmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='name',
        ),
        migrations.AddField(
            model_name='condition',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
