# Generated by Django 5.2.8 on 2026-04-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_condition_name_condition_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('story', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('rating', models.IntegerField(default=5)),
                ('conditions', models.ManyToManyField(blank=True, to='core.condition')),
            ],
        ),
    ]
